version: '3.0'
services:
  sample-firebase-nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sample-firebase-nodejs
    volumes:
      - .:/usr/src/node/app
      - ./node_modules:/usr/src/node/app/node_modules
    tty: true